services:
# Gateway
  gateway:
    extends:
      file: compose/gateway.yml
      service: gateway
    depends_on:
      - api
      - graphql
      - socket.io

  api:
    extends:
      file: compose/api.yml
      service: api

  graphql:
    extends:
      file: compose/graphql.yml
      service: graphql
# Services
  web-ui:
    extends:
      file: compose/web-ui.yml
      service: web-ui
    depends_on:
      - gateway

  socket.io:
    extends:
      file: compose/socket.io.yml
      service: socket.io

  auth:
    extends:
      file: compose/auth.yml
      service: auth

  user:
    extends:
      file: compose/user.yml
      service: user
# Infra
  rabbitmq:
    extends:
      file: compose/infra/rabbitmq.yml
      service: rabbitmq

  mongodb:
    extends:
      file: compose/infra/mongodb.yml
      service: mongodb
# Logs
  grafana:
    extends:
      file: compose/logs/grafana.yml
      service: grafana
    depends_on:
      - loki
    networks:
      monitoring: 
        aliases: [grafana]
  loki:
    extends:
      file: compose/logs/loki.yml
      service: loki
    networks:
      monitoring:
        aliases: [loki]
  promtail:
    extends:
      file: compose/logs/promtail.yml
      service: promtail
    networks:
      monitoring: 
        aliases: [promtail]
    depends_on: [loki]

volumes:
  rabbitmq-data:
  mongodb-data:
  grafana-storage: {}

networks:
  monitoring:  
    driver: bridge
    name: monitoring
    attachable: true