version: '3.8'
services:
  web-ui:
    extends:
      file: compose/web-ui.yml
      service: web-ui
    depends_on:
      - gateway

  gateway:
    extends:
      file: compose/gateway.yml
      service: gateway

  api:
    extends:
      file: compose/api.yml
      service: api

  graphql:
    extends:
      file: compose/graphql.yml
      service: graphql

  socket.io:
    extends:
      file: compose/socket.io.yml
      service: socket.io

  auth:
    extends:
      file: compose/auth.yml
      service: auth

  rabbitmq:
    extends:
      file: compose/rabbitmq.yml
      service: rabbitmq

  mongodb:
    extends:
      file: compose/mongodb.yml
      service: mongodb

volumes:
  rabbitmq-data:
  mongodb-data: