services:
# Gateway
  gateway:
    extends:
      file: compose/gateway.yml
      service: gateway
    depends_on:
      - api
      - api-test
      - graphql
      - socket.io
    networks:
      monitoring:

  api:
    extends:
      file: compose/api.yml
      service: api
    networks:
      monitoring:

  api-test:
    extends:
      file: compose/api-test.yml
      service: api-test
    networks:
      monitoring:

  graphql:
    extends:
      file: compose/graphql.yml
      service: graphql
    networks:
      monitoring:

  socket.io:
    extends:
      file: compose/socket.io.yml
      service: socket.io
    networks:
      monitoring:
        aliases: [socket.io]
    depends_on:
      - auth
      - user
      - project
      - team
# Services
  genworker:
    extends:
      file: compose/genworker.yml
      service: genworker
    networks:
      monitoring: 
        aliases: [genworker]
    depends_on:
      - mongodb
  web-ui:
    extends:
      file: compose/web-ui.yml
      service: web-ui
    depends_on:
      - gateway
    networks:
      monitoring:

  auth:
    extends:
      file: compose/auth.yml
      service: auth
    networks:
      monitoring:

  user:
    extends:
      file: compose/user.yml
      service: user
    networks:
      monitoring: 
    depends_on:
      - mongodb
  project:
    extends:
      file: compose/project.yml
      service: project
    networks:
      monitoring: 
        aliases: [project]
    depends_on:
      - mongodb
  team:
    extends:
      file: compose/team.yml
      service: team
    networks:
      monitoring: 
        aliases: [team]
    depends_on:
      - mongodb
  email:
    extends:
      file: compose/email.yml
      service: email
    networks:
      monitoring: 
        aliases: [email]
    depends_on:
      - rabbitmq
# Infra
  rabbitmq:
    extends:
      file: compose/infra/rabbitmq.yml
      service: rabbitmq
    networks:
      monitoring:

  mongodb:
    extends:
      file: compose/infra/mongodb.yml
      service: mongodb
    networks:
      monitoring:

# Logs
  grafana:
    extends:
      file: compose/logs/grafana.yml
      service: grafana
    depends_on:
      - loki
    networks:
      monitoring: 
        aliases: [grafana]
  loki:
    extends:
      file: compose/logs/loki.yml
      service: loki
    networks:
      monitoring:
        aliases: [loki]
  promtail:
    extends:
      file: compose/logs/promtail.yml
      service: promtail
    networks:
      monitoring: 
        aliases: [promtail]
    depends_on: [loki]

volumes:
  rabbitmq-data:
  mongodb-data:
  grafana-storage: {}

networks:
  monitoring:  
    driver: bridge
    name: monitoring
    attachable: true