version: '3.8'
services:
  web-ui:
    build:
      context: .
      dockerfile: services/web-ui/Dockerfile.dev
    ports:
      - "80:3000"
    volumes:
      - ./:/app
      # - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: npx nx dev web-ui

  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      # - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
      - mongodb
    command: npx nx serve api

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  rabbitmq-data:
  mongodb-data:
