services:
  graphql:
    build:
      context: .
      dockerfile: ../services/graphql/Dockerfile.dev
    ports:
      - "3002:3000"
    volumes:
      - ../:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: npx nx serve graphql