services:
  socket.io:
    build:
      context: .
      dockerfile: ../services/socket.io/Dockerfile.dev
    ports:
      - "3003:3000"
    volumes:
      - ../:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: npx nx serve socket.io