services:
  user:
    build:
      context: .
      dockerfile: ../services/user/Dockerfile.dev
    ports:
      - "3005:3000"
    volumes:
      - ../:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: npx nx serve user