services:
  web-ui:
    build:
      context: .
      dockerfile: ../services/web-ui/Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - ../:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: npx nx dev web-ui