services:
  redis:
    image: redis:7-alpine
    command: >
      redis-server
      --appendonly yes
      --save "60 1000" 
      --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    networks:
      monitoring:
        aliases: [redis]
