services:
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      monitoring:
        aliases: [redis-commander]
    ports:
      - "8081:8081"