FROM node:20

WORKDIR /app

RUN npm install -g npm@11.4.2

# COPY package*.json ./
# COPY nx.json .
# COPY tsconfig.base.json ./

# RUN npm config set fetch-timeout 60000000
# RUN npm config set fetch-retries 5
# RUN node --max-old-space-size=100000 $(which npm) ci

WORKDIR /app

# CMD ["npx", "nx", "dev", "web-ui"]
