FROM node:20

WORKDIR /app
ENV NODE_OPTIONS="--max-old-space-size=10000"

RUN npm install -g npm@11.4.2

COPY package*.json ./
COPY nx.json .
COPY tsconfig.base.json ./
# COPY ./ ./

RUN npm install

WORKDIR /app

# CMD ["npx", "nx", "dev", "web-ui"]
